### ISSUE TITLE
List Dependencies on Modrinth

### ISSUE THREAD

**Issue by catter1** [Dekunutter/eastwardjourneys#4]
Although Terrablender and Gecko are listed as dependencies in the mod description, it would be a nice QoL addition to have them as dependencies on each Modrinth version release. Especially helpful for third-party launchers that can download mods like Modrinth's App, Courseforge Launcher, Prism Launcher, etc; so they can download the dependencies as well.

![image](https://github.com/Dekunutter/eastwardjourneys/assets/63272345/8046524c-a57f-4bdf-94d0-bde153bdf956)

**Comment by Dekunutter** [comment]
Thank you for pointing this out, I'll make sure dependencies are linked to the relevant Modrinth projects for Geckolib and Terrablender soon

**Comment by Dekunutter** [comment]
This has been done, thanks again for raising this!
